{
  "$schema": "https://docs.renovatebot.com/renovate-schema.json",
  "forkProcessing": "enabled",
  "extends": [
    "config:base",
    "default:automergeDigest"
  ],
  "packageRules": [
    {
      "matchDatasources": ["go", "github-releases", "github-tags"],
      "matchUpdateTypes": ["minor", "patch", "pin", "digest"],
      "automerge": true
    }
  ]
}