version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - nlreturn
    - tagalign
    - funcorder
    - wsl_v5 # this one sucks compared to wsl.
    - noinlineerr
    - embeddedstructfieldcheck
  exclusions:
    presets:
      - comments
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
