version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - nlreturn
    - tagalign
    - funcorder
    - wsl_v5 # this one sucks compared to wsl.
    - noinlineerr
    - embeddedstructfieldcheck
  exclusions:
    presets:
      - comments
      - legacy
      - std-error-handling
    rules:
      - path: server/server_test\.go
        linters:
          - bodyclose
          - cyclop
          - dupl
          - err113
          - errcheck
          - errchkjson
          - funlen
          - gocognit
          - goconst
          - maintidx
          - mnd
          - noctx
          - revive
          - testpackage
          - unparam
          - varnamelen
          - wrapcheck
          - wsl
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
