version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - nlreturn
    - tagalign
    - funcorder
  exclusions:
    presets:
      - comments
      - legacy
      - std-error-handling
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
