name: test-and-lint
on: push
permissions:
  contents: read
jobs:
  gotest:
    # description: "Runs `go test` against 3 operating systems."
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: go-test
        run: |
          go test ./...

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
          skip: .git,go.sum,go.mod
          ignore_words_list: flate

  golangci:
    strategy:
      matrix:
        os: [linux, windows]
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.53'
